# Generated by Django 2.1.5 on 2019-01-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetguru', '0002_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='avatar',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='userId',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='topicId',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
