# Generated by Django 2.1.5 on 2019-01-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetguru', '0003_auto_20190115_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='avatar',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='fullName',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='nick',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topicId',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
