# Generated by Django 2.1.3 on 2019-01-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweetguru', '0004_auto_20190115_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitterContentId', models.BigIntegerField(unique=True)),
                ('date', models.CharField(blank=True, max_length=256, null=True)),
                ('text', models.CharField(blank=True, max_length=256, null=True)),
                ('retweetsCount', models.IntegerField()),
                ('likesCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TweetAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitterUserId', models.BigIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('fullName', models.CharField(blank=True, max_length=256, null=True)),
                ('followersCount', models.IntegerField()),
                ('friendsCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followersCount', models.IntegerField()),
                ('tweetsCount', models.IntegerField()),
                ('retweetsCount', models.IntegerField()),
                ('likesCount', models.IntegerField()),
                ('mentionsCount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Influencer',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topicId',
        ),
        migrations.AddField(
            model_name='userrank',
            name='topicId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweetguru.Topic'),
        ),
        migrations.AddField(
            model_name='userrank',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweetguru.TweetAuthor'),
        ),
        migrations.AddField(
            model_name='usermention',
            name='topicId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweetguru.Topic'),
        ),
        migrations.AddField(
            model_name='usermention',
            name='tweetId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweetguru.Tweet'),
        ),
        migrations.AddField(
            model_name='usermention',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweetguru.TweetAuthor'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='topicId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweetguru.Topic'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweetguru.TweetAuthor'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='tweetId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweetguru.Tweet'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='tweetId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweetguru.Tweet'),
        ),
    ]
