# Generated by Django 2.1.3 on 2019-01-20 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweetguru', '0004_auto_20190115_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitterContentId', models.IntegerField()),
                ('date', models.CharField(blank=True, max_length=256, null=True)),
                ('text', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TweetAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitterUserId', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('fullName', models.CharField(blank=True, max_length=256, null=True)),
                ('followersCount', models.IntegerField()),
                ('friendsCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweetguru.Tweet')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweetguru.TweetAuthor')),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweetguru.TweetAuthor'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='tweetId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweetguru.Tweet'),
        ),
    ]
