# Generated by Django 2.1.3 on 2019-01-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetguru', '0005_auto_20190121_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='tweetId',
            new_name='tweet',
        ),
        migrations.RenameField(
            model_name='searchresult',
            old_name='tweetId',
            new_name='tweet',
        ),
        migrations.RenameField(
            model_name='usermention',
            old_name='topicId',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='usermention',
            old_name='tweetId',
            new_name='tweet',
        ),
        migrations.RenameField(
            model_name='usermention',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userrank',
            old_name='topicId',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='userrank',
            old_name='userId',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='topicId',
        ),
    ]
