# Generated by Django 2.1.3 on 2019-01-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetguru', '0005_auto_20190120_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='twitterContentId',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tweetauthor',
            name='twitterUserId',
            field=models.BigIntegerField(unique=True),
        ),
    ]
