# Generated by Django 2.1.3 on 2019-01-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetguru', '0006_auto_20190121_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrank',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        )
    ]
