# Generated by Django 2.1.3 on 2019-01-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetguru', '0008_auto_20190122_1917'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrank',
            unique_together={('user', 'topic')},
        ),
    ]
